from pathlib import Path

path = Path("catalog_service.py")
text = path.read_text(encoding="utf-8")
old = '''                items = []\n                for r in leader_rows:\n                    v = json.loads(r["raw_json"])\n                    g_cnt = int(r["grp_cnt"])\n                    author_clean = str(r["author_clean"] or "")\n                    if g_cnt > 1 and author_clean and author_clean != "model":\n                        v["is_grouped"] = True\n                        v["group_count"] = g_cnt\n                        # Fetch all videos for this author in this revision matching filters\n                        member_rows = conn.execute(\n                            f"""\n                            SELECT raw_json FROM catalog_items\n                            WHERE {where_sql} AND author_clean = ?\n                            ORDER BY published_at DESC, canonical_key ASC\n                            """,\n                            params + [author_clean],\n                        ).fetchall()\n                        members = [json.loads(mr["raw_json"]) for mr in member_rows]\n                        v["grouped_videos"] = enrich_fn(members) if enrich_fn else members\n                    else:\n                        v["is_grouped"] = False\n                        v["group_count"] = 1\n                        v["grouped_videos"] = [dict(v)]\n                    items.append(v)\n\n                if enrich_fn:\n                    items = enrich_fn(items)\n'''
new = '''                # Fetch grouped members for every leader on this page in one query.\n                # The previous implementation executed one SELECT per author (up to 280\n                # extra queries on every page), which made grouped first paint much slower\n                # than the normal feed and could exceed the browser request timeout.\n                grouped_authors = [\n                    str(r["author_clean"] or "")\n                    for r in leader_rows\n                    if int(r["grp_cnt"]) > 1\n                    and str(r["author_clean"] or "")\n                    and str(r["author_clean"] or "") != "model"\n                ]\n                member_map: Dict[str, List[Dict[str, Any]]] = {}\n                if grouped_authors:\n                    member_placeholders = ",".join("?" for _ in grouped_authors)\n                    member_rows = conn.execute(\n                        f"""\n                        SELECT author_clean, raw_json FROM catalog_items\n                        WHERE {where_sql} AND author_clean IN ({member_placeholders})\n                        ORDER BY author_clean ASC, published_at DESC, canonical_key ASC\n                        """,\n                        params + grouped_authors,\n                    ).fetchall()\n                    for mr in member_rows:\n                        member_author = str(mr["author_clean"] or "")\n                        member_map.setdefault(member_author, []).append(json.loads(mr["raw_json"]))\n\n                items = []\n                for r in leader_rows:\n                    v = json.loads(r["raw_json"])\n                    g_cnt = int(r["grp_cnt"])\n                    author_clean = str(r["author_clean"] or "")\n                    if g_cnt > 1 and author_clean and author_clean != "model":\n                        v["is_grouped"] = True\n                        v["group_count"] = g_cnt\n                        members = member_map.get(author_clean, [dict(v)])\n                        v["grouped_videos"] = enrich_fn(members) if enrich_fn else members\n                    else:\n                        v["is_grouped"] = False\n                        v["group_count"] = 1\n                        v["grouped_videos"] = [dict(v)]\n                    items.append(v)\n\n                if enrich_fn:\n                    items = enrich_fn(items)\n'''
if old not in text:
    raise SystemExit("grouped query patch anchor missing")
if text.count(old) != 1:
    raise SystemExit(f"grouped query patch anchor not unique: {text.count(old)}")
path.write_text(text.replace(old, new, 1), encoding="utf-8")
print("Grouped feed batch-query hotfix applied")
